export const PAY_MPESA_REQUEST = 'PAY_MPESA_REQUEST'
export const PAY_MPESA_SUCCESS = 'PAY_MPESA_SUCCESS'
export const PAY_MPESA_FAIL = 'PAY__MPESA_FAIL'
export const PAY_MPESA_RESET = 'PAY__MPESA_RESET'

export const PAY_MPESA_CALLBACK_REQUEST = 'PAY_MPESA_CALLBACK_REQUEST'
export const PAY_MPESA_CALLBACK_SUCCESS = 'PAY_MPESA_CALLBACK_SUCCESS'
export const PAY_MPESA_CALLBACK_FAIL = 'PAY__MPESA_CALLBACK_FAIL'
export const PAY_MPESA_CALLBACK_RESET = 'PAY__MPESA_CALLBACK_RESET'
