export const TRANSACTION_LIST_REQUEST = 'TRANSACTION_LIST_REQUEST'
export const TRANSACTION_LIST_SUCCESS = 'TRANSACTION_LIST_SUCCESS'
export const TRANSACTION_LIST_FAIL = 'TRANSACTION_LIST_FAIL'

export const TRANSACTION_LIST_MY_REQUEST = 'TRANSACTION_LIST_MY_REQUEST'
export const TRANSACTION_LIST_MY_SUCCESS = 'TRANSACTION_LIST_MY_SUCCESS'
export const TRANSACTION_LIST_MY_FAIL = 'TRANSACTION_LIST_MY_FAIL'
export const TRANSACTION_LIST_MY_RESET = 'TRANSACTION_LIST_MY_RESET'